# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
future: true
lang: en-UK
title: ShefDevSoc
email: gamedev.soc@sheffield.ac.uk
description: "Sheffield Game Development Society"
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: ShefGameSoc
  picture: /assets/icons/Logo.png
twitter_username: 
github_username: ShefGameDevSoc
instagram_username: shefgamedevsoc
yt_username:
facebook_username: people/Sheffield-Game-Development-Society/100091868871243/
discord_link: https://discord.gg/h7Sgrvr48X
signup: https://su.sheffield.ac.uk/activities/view/game-development-society
logo: /assets/icons/Logo.png
search: true
search_full_content: true

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins: # previously gems
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:path/
  events:
    output: true
    permalink: /events/:path/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
      # _posts
  - scope:
      path: "_events"
      type: events
    values:
      layout: post
      read_time: false